# Basic Information 
title: Francesco Congiu
position: PhD Student
affiliation: University of Cagliari
affiliation_link: https://www.unica.it/it
affiliation_logo: ./assets/img/unica.svg
email: francesco.congiu (dot) acm 

# Search Engine Optimization (SEO)
keywords: francesco congiu, congiu francesco, francescocongiu, congiufrancesco
canonical: https://francescocongiu.com
description: Francesco Congiu is an PhD Student at the University of Cagliari. His research lies in Generative Recommender Systems, RAG and Trustworthy systems.

# The option is used to enable the Illinois template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar:
github_link: https://github.com/wakaflocka17/
linkedin: https://www.linkedin.com/in/f-congiu-res
twitter: https://twitter.com/fcongiu_res/

# Images 
avatar: https://media.licdn.com/dms/image/v2/D4D03AQHYfitXdtnyJQ/profile-displayphoto-crop_800_800/B4DZsPVIvwHkAM-/0/1765488759461?e=1767225600&v=beta&t=QOoQvOk6EdzQSMpcRkRbyoZJ9jrVlx6rO1iOHwRoZdM

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: HV0rAUdAxpfEQLOsVs0FcJTR2rKVI5sEQUZIDM-N_HY

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
